"""Generate the appendix high-stakes model table from sentence judgments.

  python analysis/high_stakes_by_model.py
Rates are sentence-weighted. Resample dialogues jointly for IF, OS and net,
retaining each metric's non-missing denominator. No significance tests.
"""
from pathlib import Path

import numpy as np
import pandas as pd

import statlib as S
from paper_numbers import HIGH_STAKES, MODEL_ORDER, load


def main():
    _, ds = load()
    assert len(ds) == 69194 and ds.dialogue_id.nunique() == 1596
    hs = ds[ds.topic.isin(HIGH_STAKES)].copy()
    assert hs.situation_id.nunique() == 22
    rows = []
    for model in MODEL_ORDER:
        sub = hs[hs.target_model == model]
        assert sub.dialogue_id.nunique() == 66
        assert sub.situation_id.nunique() == 22
        assert sub.groupby('dialogue_id', observed=True).turn_id.nunique().eq(6).all()
        values = sub[['if_any', 'os']]
        num = values.fillna(False).astype(float).to_numpy()
        den = values.notna().astype(float).to_numpy()
        clusters = sub.dialogue_id.to_numpy()
        point, lo, hi = S.cluster_boot(num, den, clusters)
        net, net_lo, net_hi, _ = S.cluster_boot_diff(
            num[:, 0], den[:, 0], num[:, 1], den[:, 1], clusters)
        assert np.allclose(point, values.mean().to_numpy(dtype=float))
        assert np.isclose(net, point[0] - point[1])
        row = dict(model=model, dialogues=66, sentences=len(sub))
        for i, name in enumerate(['IF', 'OS']):
            row.update({name: point[i]*100, name+'_lo': lo[i]*100,
                        name+'_hi': hi[i]*100, name+'_valid': int(den[:, i].sum())})
        row.update(net=net*100, net_lo=net_lo*100, net_hi=net_hi*100)
        rows.append(row)
    table = pd.DataFrame(rows)
    out = Path(__file__).resolve().parent / 'tables'
    table.to_csv(out / 'g3_high_stakes_by_model.csv', index=False)
    def cell(r, name, signed=False):
        spec = '+.1f' if signed else '.1f'
        return f"${r[name]:{spec}}$ [{r[name+'_lo']:.1f}, {r[name+'_hi']:.1f}]"
    body = '\n'.join(
        f"{r['model']} & {cell(r, 'IF')} & {cell(r, 'OS')} & {cell(r, 'net', True)} " + r'\\'
        for r in rows)
    tex = r'''% Generated by analysis/high_stakes_by_model.py
% Bootstrap resamples 10000, seed 20260913. Requires booktabs.
\subsection{Relational orientation within high-stakes topics}
\label{app:high-stakes-by-model}

We report model-level rates within the five topics designated as
high-stakes to examine how the pooled results vary across models.
Table~\ref{tab:high-stakes-by-model} gives IF and OS rates alongside
their difference.

\begin{table}[htbp]
\centering
\small
\setlength{\tabcolsep}{3pt}
\caption{Relational orientation within high-stakes topics, judged by
DeepSeek-R1-Distill-Qwen-32B. The subset includes domestic violence,
trauma, substance abuse, eating disorders, and depression.
Each model contributes 66 dialogues from 22 situations and three
disclosure personas. IF and OS are percentages of assistant sentences
with valid labels for the respective dimension. Net is IF~$-$~OS
in percentage points. Brackets give 95\% percentile confidence
intervals from 10,000 dialogue-level bootstrap resamples within
each model. Net intervals use the same resampled dialogues for
both dimensions.}
\label{tab:high-stakes-by-model}
\begin{tabular}{lccc}
\toprule
Model & IF (\%) & OS (\%) & Net (pp) \\
\midrule
''' + body + r'''
\bottomrule
\end{tabular}
\end{table}
'''
    (out / 'g3_high_stakes_by_model.tex').write_text(tex)
    print(table.round(3).to_string(index=False))
    print('Subset sentences', len(hs))
    print('Pooled rates', (hs[['if_any', 'os']].mean()*100).to_dict())


if __name__ == '__main__':
    main()
